### ISSUE TITLE
Walkmesh / NavigationMesh not implemented

### ISSUE THREAD

**Issue by benjaminfoo** [MaKiPL/OpenVIII#103]
As the title states, there is currently no such thing (an area where a player is allowed to move).
After implementation, the navmesh could be used to define/limit player-movement or execute triggers (level-change, scene-change, item-found-evenyt, etc.).

This requires that there is something like a player-model, which could be moved with different inputs.

However, i think this should be seen as low prior, as there isn't a foundation for this currently.

**Comment by Sebanisu** [comment]
Maki has models drawing for battle. I think the models are the same in field just with different animations. The save data has which model is in use and which costume. And coords where they are standing and facing I think.

**Comment by MaKiPL** [comment]
> I think the models are the same in field just with different animations
Unfortunately they are different- they are more close to World MCH than battle. Combining World (MCH) + battle (animations/skinning) would be trivial for field models. I began working on them in an independent project - https://github.com/MaKiPL/test_bootstrap_fs/tree/master/fieldmodelbootstrap but shortly after abandoned it- another bad news is that this project is not so advanced/has no good progress

**Comment by benjaminfoo** [comment]
Oh sorry, with model I meant a class or a struct which contains the model / visual. This model should then be translated / moved by inputs.
