### ISSUE TITLE
worldmap world wrapping has missing faces

### ISSUE THREAD

**Issue by MaKiPL** [MaKiPL/OpenVIII#124]
![world wrap issue](https://cdn.discordapp.com/attachments/552838120895283210/615999958595665947/unknown.png)

Something with frustrum cull?

**Comment by MaKiPL** [comment]
not frustum view- something else is bad

**Comment by MaKiPL** [comment]
Okay- I know what's the deal
```                    for (int k = 0; k < waterSeg.parsedTriangle.Length; k+=3)```
should be:
```                    for (int k = 0; k < waterSeg.parsedTriangle.Length; k++)```

but it's heavy on optimalization. Instead I'm thinking to NOT draw segment0, but one plain with UV set to repeat the water plane

**Comment by MaKiPL** [comment]
![New water warping schema](https://i.postimg.cc/D0xhprWm/new-Water-Warping.png)

water warping to be reimplemented from beginning basing on real-warped segments, not water. Above full warp schema.

**Comment by benjaminfoo** [comment]
Noble solution 👍
