### ISSUE TITLE
BattleCamera flys off to nowhere (black screen)

### ISSUE THREAD

**Issue by Sebanisu** [MaKiPL/OpenVIII#130]
If you push 4 and move through the different battles, sometimes the camera goes black and flys off to god knows where.  You can avoid this somewhat by going to the fps camera.

**Comment by MaKiPL** [comment]
Related to #92 - cam mode 0 is not yet fully investigated. Please ignore that for now on. 😢

**Comment by Sebanisu** [comment]
lol, no big deal just wanted to make a note of it :)
