### ISSUE TITLE
MODULE_OVERTURE_DEBUG: Playing overture again doesn't work

### ISSUE THREAD

**Issue by MaKiPL** [MaKiPL/OpenVIII#15]
Selecting> OpenVIII debug tools>Play overture
doesn't play overture but get's back to main menu

**Comment by Sebanisu** [comment]
somehow I deleted the Memory.module = Memory.MODULE_OVERTURE_DEBUG; while I was adding the code to play the squaresoft logo. I put it back in my copy.

**Comment by MaKiPL** [comment]
Fixed in #d22a993 - Thank you, closing
