### ISSUE TITLE
add appveyor build bot

### ISSUE THREAD

**Issue by shikulja** [MaKiPL/OpenVIII#152]
convenient for checking assemblies, especially those who do not have space to install vc

**Comment by Sebanisu** [comment]
I'll give it a try on my fork.

**Comment by Sebanisu** [comment]
https://github.com/Sebanisu/OpenVIII/releases/tag/Canary i got it making something atleast :P

**Comment by shikulja** [comment]
> https://github.com/Sebanisu/OpenVIII/releases/tag/Canary i got it making something atleast :P

not work. empty log.

**Comment by shikulja** [comment]
you need to remove the x86 library from the x64 assembly, as well as the linux .so library

**Comment by Sebanisu** [comment]
ran fine... the log was disabled. we don't have a config file to turn things on and off. It's a const variable. Extra files don't hurt anything they just take up hard drive space.

**Comment by Sebanisu** [comment]
I have 4 windows builds working x86/x64 for OpenGL and DirectX though bugs reported as there will be bugs. Working on Ubuntu.

**Comment by shikulja** [comment]
update nuget pakages give errors
![Снимок](https://user-images.githubusercontent.com/3386359/75872280-ec9d8f00-5e1e-11ea-8b17-7bc565520ca3.PNG)
on VM WIN7 debug build opengl work. on real w10 not work, with empty log

**Comment by Sebanisu** [comment]
cannot update nuget packages new versions aren't compatable

**Comment by shikulja** [comment]
> Cannot update nuget packages new versions aren't compatible. Because the midi library requires a custom build of a library. Maki has a pull request to get the mod added to the main branch but we've been waiting for a while on that. Because by default the library can only write midi files. Where we needed it to be a stream so we didn't need to waste time writing to the hard drive and reading it off that.

sad news.

what with .log did not look? any ideas?

**Comment by Sebanisu** [comment]
it found your ff8dir.
the log doesn't really show anything out of ordinary. though it stopped at extracting sysfnt.tex
Might need a copy of the exception thrown.
log file does show what ff8 dir it is using.
1::Memory :: FF8DIR = C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY VIII

**Comment by shikulja** [comment]
> it found your ff8dir.
> the log doesn't really show anything out of ordinary. though it stopped at extracting sysfnt.tex
> Might need a copy of the exception thrown.
> log file does show what ff8 dir it is using.
> 1::Memory :: FF8DIR = C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY VIII

I realized the unfinished font .. in the original game it worked, though it's bad ..

**Comment by Sebanisu** [comment]
I'm gonna close this issue. It might be on my fork and not on master but i think if we want it on master it should be setup with maki's own appveyor account so they have main control over it.
