### ISSUE TITLE
Coding style

### ISSUE THREAD

**Issue by FlameHorizon** [MaKiPL/OpenVIII#165]
To keep the same formatting across the entire project and multiple users project can use `.editorconfig` file. I never worked with Clnag Tidy file but looks similar. `editorconfig` can define code style settings which will be associated with a codebase rather than a Visual Studio personal account. To read more more about code styles in VS 2017 [follow this link](https://docs.microsoft.com/en-us/visualstudio/ide/code-styles-and-code-cleanup?view=vs-2017#code-styles-in-editorconfig-files)

ReSharper is also able to work with defined `.editorconfig` file. But it looks like ReSharper have broader range of checks than default config file.

Choices are:
- `editorconfig` is included in project but it replaces checks done by ReSharper
- rely on ReShaper to do code consistence checks, but there are people who does not have RS installed. 

Let me know what do you think.

Related #98

**Comment by Sebanisu** [comment]
I guess I can export what I have set to the file.  Then we can be on the same settings. And I guess you guys can tweak it if needed.

**Comment by FlameHorizon** [comment]
Sounds fair.

**Comment by FlameHorizon** [comment]
#169 contains ‘editorconfig’ file. I’m closing this PR.
