### ISSUE TITLE
TEX: non-clut bgra5551 is actually rgba5551

### ISSUE THREAD

**Issue by MaKiPL** [MaKiPL/OpenVIII#3]
MonoGame/XNA doesn't know what BGRA is and treats bgra5551 as rgba5551- looks like I may need to swap RGB<>BGR manually

**Comment by Sebanisu** [comment]
I just saved all of the frames of disc00_00h. For testing purposes I've been processing the whole video and exporting all the frames to files. I have a class a started with ffmpeg. I think can I correct the color then I Just need make it so you can go on the next frame one at a time. Then I can just pull out Aforge as we won't need it. This has been a learning process.

**Comment by Sebanisu** [comment]
Okay color corrected and replace functionality of Aforge we were using.

**Comment by Sebanisu** [comment]
I think this can be closed now. I'm not 100 precent sure the colors are right but I think it looks good.
