### ISSUE TITLE
Choose an open source license

### ISSUE THREAD

**Issue by Albeoris** [MaKiPL/OpenVIII#34]
Right now the project doesn't have a license.

> When you make a creative work (which includes code), the work is under exclusive copyright by default. Unless you include a license that specifies otherwise, nobody else can copy, distribute, or modify your work without being at risk of take-downs, shake-downs, or litigation. Once the work has other contributors (each a copyright holder), “nobody” starts including you.
> 
> If you find software that doesn’t have a license, that generally means you have no permission from the creators of the software to use, modify, or share the software. Although a code host such as GitHub may allow you to view and fork the code, this does not imply that you are permitted to use, modify, or share the software for any purpose.

I propose to [choose one of the most open licenses](https://choosealicense.com/), if it doesn't contradict the original plan.

The **MIT License** is short and to the point. It lets people do almost anything they want with the project.

**Comment by MaKiPL** [comment]
Added MIT license
