### ISSUE TITLE
What kind of licenses can we use in this project?

### ISSUE THREAD

**Issue by Albeoris** [MaKiPL/OpenVIII#35]
Some kinds of licenses make the product dirty.

For example, the GNU GPLv3 lets people do almost anything they want with your project, **except** to distribute closed source versions. 

At the same time, there are [ready-made solutions](https://github.com/myst6re/deling), the use of which code can simplify life.

Is there a limit to the kinds of licenses that we can use during development?

**Comment by MaKiPL** [comment]
I just simply want it to remain open-source, so GNU GPLv3 is perfect in my opinion

**Comment by Albeoris** [comment]
Then we have to add license text to the header of each file that is licensed by the GPL. :(

**Comment by benjaminfoo** [comment]
I second this + its really no effort to get this issue closed 👍

**Comment by MaKiPL** [comment]
Related to #34  - closed. MIT license added.
