### ISSUE TITLE
FluidSynth: awaiting DLS support

### ISSUE THREAD

**Issue by MaKiPL** [MaKiPL/OpenVIII#39]
Awaiting for FluidSynth support for DLS
https://github.com/FluidSynth/fluidsynth/pull/493#issue-241490246

**Comment by MaKiPL** [comment]
It's now on master. Proceeding with linux music

**Comment by Sebanisu** [comment]
Cool. One thing I need to do is make it easier to swap between the midi and
ogg music. Right now if raw is installed it kinda overrides the midi unless
there isn't an ogg track.
