### ISSUE TITLE
init_debugger_audio: SoundID 28 not playing

### ISSUE THREAD

**Issue by MaKiPL** [MaKiPL/OpenVIII#4]
ADPCM + stereo + normal sample rate
Totally no idea why it's not playing. It's the only sound that is not playing at all.

Current workaround is to force PCM decoding on this chunk, but it will produce glitches

**Comment by Sebanisu** [comment]
ReadTimeout = 'a.ReadTimeout' threw an exception of type 'System.InvalidOperationException'
WriteTimeout = 'a.WriteTimeout' threw an exception of type 'System.InvalidOperationException'

for some reason these exceptions only show while debugging and looking at the Stream's members. Maybe it's a bug with Naudio?

**Comment by Sebanisu** [comment]
[sound28.zip](https://github.com/MaKiPL/OpenVIII/files/3036190/sound28.zip)
After exporting the sound to a wav file I got to hear it. I wasn't sure if it sounded right. Because I'm unsure what the sound is supposed to sound like.

**Comment by MaKiPL** [comment]
Good job on resolving this one! I'm marking this as fixed, thank you
