### ISSUE TITLE
init_debugger_audio: DirectMusic not natively supported 

### ISSUE THREAD

**Issue by MaKiPL** [MaKiPL/OpenVIII#7]
DirectX 6 DirectMusic not natively supported with Unix. What now?
EDIT: I talk about DirectMusic .DTS and .SGT files.
Currently I'm wrapping real DX6 component. Linux may probably require pre-converted OGG sounds. 

EDIT:

- [ ] Implement loops
- [x] Fix tempo *
- [ ] Add curves support
- [ ] Investigate WAVE effects
- [x] Implement custom NAudio library for in-memory song writing
- [ ] Maintain final quality

*Pulse per note = tick per note; milliseconds = 60 000 / (BMP * PPQ). Now: 120 * 2000 ?

**Comment by MaKiPL** [comment]
NAudio which we use is capable to forge a Midi messages and is capable of supporting all important messages. Therefore it may be possible to actually convert SGT segments to real buffered Mdi event collections. That may require digging up the deprecated documentation of segments. Question is if it's really worth the probably huge amount of time to introduce DirectMusic converter

**Comment by Sebanisu** [comment]
cool :)

**Comment by MaKiPL** [comment]
Got the music working without using DirectMusic by parsing SGT file into sequence and translating to MIDI messages. See example state at: 
https://github.com/MaKiPL/OpenVIII/commit/b3a7785f449398b23fdf246fbf4b5e4ea5163e29
the all tempo and things like that are constant, I just wanted to play the notes, not caring for the tempo, speed and instruments. Playback would be probably provided with FluidSynth or NAudio for both Linux and Windows just to delete use of the deprecated directmusic at all

**Comment by MaKiPL** [comment]
some notes so I don't forget:

1. seqt[n].mTime is sorted - that's good, no need for Linq every note as in prototype. 
2. seqt[n].mDuration should be put on a list for a note and channel and then noteoff'd 
3. seqt[n].dwPChannel has already a channel pointer- that's very good
4. seqt[n].bByte1 is note
5. seqt[n].bByte2 is velocity
6. seqt[n].bStatus is MID event, but it's always 144=noteOn

Tempo is double, but it reports weird values. Maybe it's not double or something? 

Thread:
init_debugger_audio on init should create Thread. The thread should get messages from the engine. Every PlayMusic should clear the sequence and stop the internal MIDIEvents. The thread should also GC pin the unmanaged variables.

Performance:
The segment reading is faster than vanilla DxMusic

**Comment by MaKiPL** [comment]
segh::mTime```

0: 62208
1: 44544
4: 154368
5: 185856
79:329024 (demo)
93:467712 (lasboss)
```

**Comment by MaKiPL** [comment]
- [ ] Handle tempo correctly
- [ ] Handle mDuration (/noteoff) faster way than operations on List<>
- [ ] Handle curves if needed
- [ ] Recompile library for Windows AMD64
- [ ] Handle loops

**Comment by MaKiPL** [comment]
I wonder if creating a MIDI itself wouldn't be faster and more stable than handling the operations on my own. Currently I have to implement a thread with tempo, curves and all that stuff, but on the other hand I can create a .mid in memory and whole synth will do it on it's own 'their way' (which I'm more than sure is way faster). Afair NAudio has whole MIDI creation class.

**Comment by MaKiPL** [comment]
DMUS_IO_TIMESIGNATURE may be wrong. The structure sizeof=8, but the algorithm reads actually (sectionLength-4) / 2 where it should be divide by 8. I just got a lot of rubbish in tims and noticed this error. Finally we lack the formulas for converting the time signature events to MIDI like- worth to follow libdmusic code to find out how the tempo and timing is parsed

**Comment by MaKiPL** [comment]
*TEMPO notes:
DMUS_PPQ is const 768
Calcs: 60 000 000 (BPM*PPQ)?
Current example: 120*2000 = 240 000
QuarterNote is set to 360 for now
Let N= 2000 in (120*2000)
>N - slower
<N - faster

**Comment by MaKiPL** [comment]
OpenVIII now uses custom NAudio library with my extension: https://github.com/naudio/NAudio/pull/499
to write Midi to memory instead of HDD for fluid_player_add_mem

**Comment by MaKiPL** [comment]
DirectMusic segments are now played in X64 and linux. It's still WIP, I'm making new issue
