### ISSUE TITLE
FF8String vs FF8.Encoding

### ISSUE THREAD

**Issue by MaKiPL** [MaKiPL/OpenVIII#82]
Currently we have at the moment two classes that provide the text encoding/decoding. No need for redundancy. I'd go with FF8.Encoding as it supports different chartables, has encoding capabilities and already have support for tags.

**Comment by Sebanisu** [comment]
okay sounds good I'll go over the new chart table and make sure everything is there and delete mine.

**Comment by Sebanisu** [comment]
Though ff8 string is just a helperclass it uses dirtyencoder to translate the strings. I can make ff8string use the new encoder i think? i'll look at it.

**Comment by Sebanisu** [comment]
I think it's mostly fixed now but could be more to do. I haven't even gotten to a point where we are drawing strings with tags in them yet except for the locations but I read those out of kernel and namedic. overtime we'll merge that code as we find places to do so I guess.
